### ISSUE TITLE
Mitsuba renderings

### ISSUE THREAD

**Issue by danielwinkler** [doyubkim/fluid-engine-dev#100]
The Mitsuba renderings in the examples video and the book look great.
Is it possible to add the Mitsuba project files and possibly scripts that were used to create these images?
Unfortunately I only see the volume export for smoke simulations in the source code.

**Comment by doyubkim** [comment]
Great suggestion. I actually have a private repo with Mitsuba scene files but it's super messy right now. Let me clean that up and make public.

**Comment by danielwinkler** [comment]
Great.
Thank you very much!

**Comment by marcelsan** [comment]
Which kind of file is provided to Mitsuba render in order to render fluid simulations?

**Comment by doyubkim** [comment]
Hi @marcelsan,

* For liquids, I used simple obj mesh files to represent fluid surface. 
* To render particles directly, particle2xml tool can be used for exporting particle position data to bunch of tiny spheres in Mitsuba format. 
* For volumetric data such as smoke, Mitsuba defines its own volume data format. You can find the file exporter under smoke_sim example.

**Comment by marcelsan** [comment]
@doyubkim 
How can I help you with this issue?

**Comment by doyubkim** [comment]
@marcelsan, thank you for suggesting your help! This particular issue can be closed once I finish cleaning up my existing private repo that contains the Mitsuba scene files that I used for the book. However, once that's finished, we can think of adding more scene files for further example/demo simulations. Can you help me on that? I will create another ticket once I close this one.

**Comment by marcelsan** [comment]
@doyubkim sure!

Moreover, I was thinking about adding multiple phase simulation. What do you think about this?

**Comment by doyubkim** [comment]
@marcelsan, great! I will open an issue to cover that work.

**Comment by doyubkim** [comment]
I created another repository (https://github.com/doyubkim/fluid-engine-dev-demo) to host the rendering files.
