### ISSUE TITLE
Need a null pointer check in ImplicitSurfaceSet3::closestPointLocal

### ISSUE THREAD

**Issue by GameLogicDesign** [doyubkim/fluid-engine-dev#156]
If a ImplicitSurfaceSet3 is empty and has no surfaces, then the bvh will have no nodes. Calling the function ImplicitSurfaceSet3::closestPointLocal will then crash since the queryResults item is null.

const auto queryResult = _bvh.nearest(otherPoint, distanceFunc);
return (*queryResult.item)->closestPoint(otherPoint);

**Comment by doyubkim** [comment]
Thanks for finding this! Working on the fix now.

**Comment by doyubkim** [comment]
Should be fixed by #157
