### ISSUE TITLE
Crash building TriangleMesh BVH inside ParallelFor

### ISSUE THREAD

**Issue by GameLogicDesign** [doyubkim/fluid-engine-dev#159]
I am building using JET_TASKING_CPP11THREADS.

If you create an emitter from a TriangleMesh3 and add it to a LevelSetLiquidSolver3 as an ImplicitSurface3 using SurfaceToImplicit3, then when you do the solver update it will crash in a ParallelFor since multiple threads are triggering the build of the bvh.

To work around this you can call updateQueryEngine() for each emitter. 

However the above is obviously the wrong approach since if you use a ImplicitTriangleMesh3 the issue does not present itself. But I thought I would point it out in case another user hits the same bug when getting started.

**Comment by doyubkim** [comment]
Thanks for filing another great issue! Function `updateQueryEngine()` is there for that exact purpose and it should be called for emitters, not just for colliders. Will push the fix soon.
