### ISSUE TITLE
Fix link error problem in mem_perf_tests

### ISSUE THREAD

**Issue by utilForever** [doyubkim/fluid-engine-dev#167]
If you have the latest version of ```googletest```, you will get link errors when building the ```mem_perf_tests``` project. This problem is caused by the ```ColoredPrintf``` function becoming a ```static``` function. I'll fix it.

**Comment by doyubkim** [comment]
Current ColoredPrintf is actually a hack. Would be great if we can replace it with a version that does not depend on gtest.

**Comment by utilForever** [comment]
There are several solutions. For example:
```
#include <iostream>

...

TEST(FDMICCGSolver3, Memory)
{
    ...
    const auto msg = MakeReadableByteSize(mem1 - mem0);

    std::cout << "Mem usage: " << msg.first << ' ' << msg.second.c_str() << ".\n";
}
```

**Comment by doyubkim** [comment]
Coloring would be ideal, but not necessary. I actually would like to rewrite the memperf tests in general (using gtest is just another hack). In order to make future transition (i.e. remove gtest dependency), let's use simple wrapper function around printf, such as:

```cpp
void printMemReport(size_t memUsage, const std::string& memMesage) {
    printf("Mem usage: %zu %s\n");
}

...

TEST(FdmIccgSolver3, Memory) {
    ...
    const auto msg = makeReadableByteSize(mem1 - mem0);

    printMemReport(msg.first, msg.second);
}

```

**Comment by utilForever** [comment]
Okay. I am going to modify the code using the above method and then pull request.
