### ISSUE TITLE
Codecov support

### ISSUE THREAD

**Issue by utilForever** [doyubkim/fluid-engine-dev#177]
```Codecov``` is an online platform that provides hosted testing reports and statistics for its users. It supports ```googletest``` and ```pytest``` and free for open sources. This will help you measure code coverage.
- Codecov : https://codecov.io

**Comment by utilForever** [comment]
I added Codecov to CubbyFlow-v0 (https://codecov.io/gh/utilForever/CubbyFlow-v0).
I'll be working on the Jet Framework soon. Please wait a moment for me to prepare for the presentation tomorrow.

**Comment by doyubkim** [comment]
Let's separate the task into two: 
1) Let's make `lcov` working (#178) and 
2) Integration to Codecov. 

I just created my account for Codecov so setting up the webhook should be straightforward. Once your PR for #178 gets raised and merged, I will take care of the integration part.

**Comment by utilForever** [comment]
Okay. I'll work on weekend.
