### ISSUE TITLE
Test coverage report for C++ API

### ISSUE THREAD

**Issue by doyubkim** [doyubkim/fluid-engine-dev#178]
Related to #177, incorporate gcov/lcov. Good example can be found from: https://github.com/codecov/example-cpp11-cmake

**Comment by utilForever** [comment]
I added codecov to Hearthstone++ project. (https://github.com/utilForever/Hearthstonepp)
I will help you. :)

**Comment by doyubkim** [comment]
Great! Assigned to @utilForever

**Comment by doyubkim** [comment]
@utilForever any updates on this? Just checking in, no pressure :)

**Comment by utilForever** [comment]
@doyubkim Oh, sorry. I'm working a very busy days due to the summer vacation period.
I'll take a moment to work on the weekend. Please wait a minute. 😭

**Comment by doyubkim** [comment]
@utilForever hey no worries! I was just checking in. No need to rush.

**Comment by utilForever** [comment]
@doyubkim Oh, of course I know. Just think I don't be lazy and put up the hare. :<
