### ISSUE TITLE
cannot compile correctly

### ISSUE THREAD

**Issue by heavenisaplaceonearth** [doyubkim/fluid-engine-dev#187]
Greetings I have a trouble to compile your scripts by cmake

I followed whole instruction and I got error

the following is the error

CMake Error at CMakeLists.txt:73 (add_subdirectory):
  The source directory

    C:/Users/id/Desktop/Research/fluid-engine-dev-master/external/googletest

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:78 (add_subdirectory):
  The source directory

    C:/Users/id/Desktop/Research/fluid-engine-dev-master/external/googlebenchmark

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:98 (add_subdirectory):
  The source directory

    C:/Users/id/Desktop/Research/fluid-engine-dev-master/external/pybind11

  does not contain a CMakeLists.txt file.

CMake Error at src/python/CMakeLists.txt:22 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

Configuring incomplete, errors occurred!
See also "C:/Users/id/Desktop/Research/fluid-engine-dev-master/build/CMakeFiles/CMakeOutput.log".

and I`ll upload my log file too

[CMakeOutput.log](https://github.com/doyubkim/fluid-engine-dev/files/2276652/CMakeOutput.log)

Error occurs due to the lack of files in some folders in external directory

I checked whole project file to check integrity but seems fine

there are empty folders in influid-engine-dev-master\build\external\

which name are googlebenchmark, googletest, etc

how to solve this error sir?

**Comment by doyubkim** [comment]
Hello!

Try running the following:

    git submodule update --init

It will clone the dependencies into the empty directory.

**Comment by heavenisaplaceonearth** [comment]
@doyubkim Thank you for your prompt answer. It solved by direct downloading through git. But I met another barrier. I followed window installation instruction but got error in

MSBuild jet.sln /p:Configuration=Release

below is one of the error message

emitter.cpp) [C:\Users\id\Desktop\Research\fluid-engine-dev\build\src\pytho
n\pyjet.vcxproj]
  c:\users\id\desktop\research\fluid-engine-dev\external\pybind11\include\p
ybind11\common.h : error C2220: warning treated as error - no 'object' file generated(compiling C:\Users\id\Desktop\Research\fluid-engine-dev\src\python\zhu_bridson_poin

There are many same errors displayed on CMD

I have searched C2220 error and used some trick to resolve

to ignore error, I added WarningLevel=0

and executed below

MSBuild jet.sln /t:rebuild /p:Configuration=Release;WarningLevel=0 /flp:Encoding=Unicode

But the result was not changed.

got 90 errors and example codes don`t work

How to deal with this case sir

**Comment by doyubkim** [comment]
Hmm that is strange. What was your CMake parameter? Was it `-G"Visual Studio 15 2017 Win64"? Can you attach the error log that contains the "warning" message (which triggers the C2220 error)?

**Comment by doyubkim** [comment]
Closing this issue for now since the CI is working fine. Please reopen this issue if the problem still occurs.
