### ISSUE TITLE
Slight typos in Vector4-inl.h

### ISSUE THREAD

**Issue by TAMREF** [doyubkim/fluid-engine-dev#194]
Hello!
I'm studying how to build Math Library from your repository. I appreciate your efforts.
While reading the source code, I found something looks like a typo in your details/Vector4-inl.h :

Especially, maybe the fifth line for the functions `dominantAxis()` and `subminantAxis()` (Line 264 and Line 275 in the original file) should be modified from `std::fabs(x) > (or <) std::fabs(w) ? 2 : 3`to
`std::fabs(z) >(or <) std::fabs(w) ? 2 : 3`.

Also, there are few typos in the comments written in your Vector4.h, remaining that came from Vector3.h.
I'm a novice in developing and Git-using, so forgive me if my request was rude or ignorant :(
I'll send you a pull request with modified files, if you want.

**Comment by utilForever** [comment]
Thanks! I'll check it.

**Comment by doyubkim** [comment]
Yep, that’s a bug. Thank you for reporting this!

**Comment by utilForever** [comment]
@doyubkim Thanks. I'll work on this weekend. Please understand that my health is not very good.

**Comment by utilForever** [comment]
@doyubkim Thanks. I'm OK now. So, please take this issue to me. 😄

**Comment by doyubkim** [comment]
I actually have a fix for this. Would be great if @utilForever can review the PR.
