### ISSUE TITLE
ImplicitSurfaceSet3's closest point doesn't seem to work correctly

### ISSUE THREAD

**Issue by ryanastout** [doyubkim/fluid-engine-dev#196]
In the sph_sim example, there are 3 different examples. For examples 1 and 2, the emitter is a sphere at (.5, 1, .5) with radius .15 and a plane with normal (0, 1, 0) and point (0, .5, 0). However, calling
 
surfaceSet->closestPoint(Vector3D{.5, .4,.5});
returns a Vector3D at  (0.5, 0.85, 0.5) which is a point on the sphere despite (.5, .5, .5) being on the plane and closer to the queried point.

I believe there's a bug in ImplicitSurfaceSet3::closestPointLocal() but I'm not 100% sure where and I didn't have time to track it down (at least not for now). 

I described this issue in https://github.com/doyubkim/fluid-engine-dev/pull/195, but I'm writing it here as well.

**Comment by doyubkim** [comment]
Thanks for reporting this! I will take a look.

**Comment by doyubkim** [comment]
Work around fix by @ryanastout is merged, but it does not fix the fundamental problem where unbounded types such as plane is added to a (implicit) surface set. Will keep this issue open until I raise another PR to address that issue.
