### ISSUE TITLE
PicSolver error when no Collider is present

### ISSUE THREAD

**Issue by kentbarber** [doyubkim/fluid-engine-dev#200]
If you are running a PicSolver simulation but have no colliders added then in the call  PicSolver3::moveParticles(...) it does the following...

Collider3Ptr col = collider();
if (col != nullptr)
{
  //A valid pointer is still returned, it just contains no surfaces or unbounded surfaces
}

This then causes issues when the call to resolveCollision is made since it makes a call to Collider3::getClosestPoint, but the Surface3Ptr passed in doesn't actually have any surfaces.

So the following call to Surface3::closestDistance, which in turn calls 

ImplicitSurfaceSet3::closestDistanceLocal.

Since there are no surfaces the queryResult returned from the _bvh returns the maximum distance. 

This then ends up setting all the particle positions to this maximum value because in the

Collider3::resolveCollision(...)  method it assumes that 

 getClosestPoint(_surface, *newPosition, &colliderPoint);

actually returned a valid result for the colliderPoint. But since it doesn't then it enters the method

if (isPenetrating(...))

which in turn sets the particle positions all to be the maximum value.

I think checks should be made through all these methods, but a quick fix would be to return a boolean from Collider3::getClosestPoint if there are no surfaces and then return from the function Collider3::resolveCollision() without doing anything.

**Comment by doyubkim** [comment]
Thanks for reporting this! Will take a look over the weekend.

**Comment by doyubkim** [comment]
Freshly created PicSolver3 instance won't have any collider assigned, but I think what you are doing here is that have a collider with empty ImplicitSurfaceSet3 so that your code can dynamically add surfaces to the collider.

What I'm going to do is to double check from collider so that empty-surface collider doesn't try resolving any collisions, similar to what you proposed.

**Comment by kentbarber** [comment]
Yes that is correct. Although I haven't specifically worked on dynamically adding colliders at this stage. Sorry about that, I should have mentioned my specific setup along with the report.

```
std::vector<jet::ImplicitSurface3Ptr> colliderSurfaces;
auto colliderSet = jet::ImplicitSurfaceSet3::builder().withSurfaces(colliderSurfaces).makeShared();
auto colliderRigidBodies = jet::RigidBodyCollider3::builder().withSurface(colliderSet).makeShared();
solver->setCollider(colliderRigidBodies);
```

**Comment by doyubkim** [comment]
Thanks, @kentbarber for the code. The PR #201 should fix the problem. Please reopen this issue if it still happens after the merge.
