### ISSUE TITLE
Project is not compiled in Release mode

### ISSUE THREAD

**Issue by PavelBlend** [doyubkim/fluid-engine-dev#217]
I have a Visual Studio 2017 Community.
In Release mode, the project refuses to compile.
Not enough memory.
I have 8 GB Windows 7 64 bit.

In Debug mode, the compilation is successful.

**Comment by doyubkim** [comment]
Can you try building a single project/target, not the full solution? Also, I wonder if turning off multithreaded build helps in this case. CCing @utilForever in case he encountered similar issues before.

**Comment by PavelBlend** [comment]
> Can you try building a single project/target, not the full solution?

did not help.
I built pyjet and got an error:

https://docs.microsoft.com/ru-ru/cpp/error-messages/compiler-errors-1/fatal-error-c1002?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DRU-RU%26k%3Dk(C1002)%26rd%3Dtrue&view=vs-2017

When I collect the entire solution, the compiler produces this error on the unit_tests project.

**Comment by PavelBlend** [comment]
It was possible to assemble in MinSizeRel mode.
How will this build differ from the Release build in terms of speed?

**Comment by utilForever** [comment]
@PavelBlend I think it's an error caused by a lack of memory. MinSizeRel is the same as Release, with its optimization configuration just set to Minimize size, Maximize speed in Visual Studio.

**Comment by doyubkim** [comment]
I can now reproduce this issue on a Windows machine with 16 GB of RAM and VS 2017. Not sure this is VS 2017 specific problem, but let me dig in a bit more.

**Comment by utilForever** [comment]
@PavelBlend What is your version of Visual Studio?

**Comment by PavelBlend** [comment]
@utilForever 15.6.1

**Comment by utilForever** [comment]
@PavelBlend Two months ago, I encountered pybind11 compile error on VS 15.8 and VS 15.9 preview. It was ICE(Internal Compiler Error) and fixed 15.9. Could you update VS 2017?

**Comment by utilForever** [comment]
I built Jet framework in Surface Book 2 and found no problem.
(16GB RAM and Visual Studio 2017 15.9)

**Comment by PavelBlend** [comment]
Updated VS and it turned out to compile in Release mode.
