### ISSUE TITLE
Resume Baking

### ISSUE THREAD

**Issue by PavelBlend** [doyubkim/fluid-engine-dev#219]
At the moment there is an opportunity to resume baking?
I tried to add particles from the cache using particleSystemData.addParticles, but for some reason the particles are not where they are needed.

**Comment by doyubkim** [comment]
You can serialize data with particleSystemData.serializeToFile and reload it again with deserializeFromFile.

**Comment by doyubkim** [comment]
How many particles are there in your scene? The cache file contains binary version of positions and velocities arrays in 64-bit float type.

**Comment by PavelBlend** [comment]
> How many particles are there in your scene?

1551. File cache weighs 4.2 MB
My file cache weighs 110 KB in one frame and 935 KB in 30 frames.

Does the serializeToFile function save particles from the active frame or save particles from all frames?

**Comment by doyubkim** [comment]
Just checked with small number of particles and there seems to be a bug somewhere around FlatBuffer-based serialization. (It adds 4MB by default.) This weird chunk of bytes doesn't seem to grow as # of particles increase, but is definitely a bug and will look into. 

In the meantime, can you try the following method to save and restore particles? The example below copies the current particle state, clears the particles (`resize(0)`) and then restore the state by adding the particles back.

```
pos = np.array(solver.particleSystemData.positions, copy=False)
vel = np.array(solver.particleSystemData.velocities, copy=False)
frc = np.array(solver.particleSystemData.forces, copy=False)

new_pos = [x.tolist() for x in pos]
new_vel = [x.tolist() for x in vel]
new_frc = [x.tolist() for x in frc]

solver.particleSystemData.resize(0)
solver.particleSystemData.addParticles(new_pos, new_vel, new_frc)
```

**Comment by doyubkim** [comment]
I just remembered that particle system data also serializes its neighbor searcher (hash grid). So if you want to bake the particles only, use the method I provided above.
