### ISSUE TITLE
Animating parameters

### ISSUE THREAD

**Issue by PavelBlend** [doyubkim/fluid-engine-dev#220]
Is it possible to animate during the simulation?
For example, enable the oneShot parameter at the emitter, and then after 10 frames turn it off.
Or change the position of the collider.
Or change the initial velocity at the emitter.

**Comment by doyubkim** [comment]
Hi Pavel!

1. isOneShot is not exposed to the Python API yet. 
2. Changing the position and orientation of the collider can be done by setting `Transform3` to the source surface mesh (`.transform` property). You also need to provide `collider.linearVelocity` (and `collider.angularVelocity` if rotating) as well.
3. Initial velocity of the emitter is also not exposed to the Python API yet.

Let me come up with a PR to expose some APIs (1 and 3 above) as well as code examples for 2.

**Comment by doyubkim** [comment]
@PavelBlend: PR is out. Check out the new example script. You might need the other PR (#218) merged to run your code. @utilForever, I will merge #218 soon if you don't have any major concern.

**Comment by doyubkim** [comment]
PR with new APIs and an example code is now merged

**Comment by PavelBlend** [comment]
How to make the emitter move? VolumeParticleEmitter3 does not have a linearVelocity property.

**Comment by doyubkim** [comment]
@PavelBlend: It is possible to do so, but not quite efficient. Let me open another issue for that.

**Comment by PavelBlend** [comment]
> 2\. Changing the position and orientation of the collider can be done by setting `Transform3` to the source surface mesh (`.transform` property). You also need to provide `collider.linearVelocity` (and `collider.angularVelocity` if rotating) as well.

And how to make colliders move in different directions?
The linearVelocity parameter is common to all colliders.
I use a lot of colliders in the form of ImplicitTriangleMesh3, and then assign them to the solver using SurfaceSet3. I need to control each mesh of the collider separately.

**Comment by doyubkim** [comment]
@PavelBlend it requires ColliderSet3 which is missing from Python API. Let me add it with some examples shortly.

**Comment by PavelBlend** [comment]
For some reason, I can't get the emitter to move.
I specify linearVelocity, and this parameter behaves like initialVelocity.

**Comment by doyubkim** [comment]
Hi @PavelBlend, can you try the example (`src/examples/python_examples/collider_emitter_anim_example.py`) and see if it moves? Are you setting `surface.transform` as well?

**Comment by PavelBlend** [comment]
Checked The example works correctly. But I can't do this in blender. I use surface.transform.

**Comment by PavelBlend** [comment]
Understood with translation. Everything works correctly.

**Comment by doyubkim** [comment]
@PavelBlend, it should be possible with `ColliderSet3` (add multiple colliders using `ColliderSet3.addCollider` and control individual sub-colliders). Let me know if that doesn't work.
