### ISSUE TITLE
Leaking SDF from ImplicitTriangleMesh3

### ISSUE THREAD

**Issue by doyubkim** [doyubkim/fluid-engine-dev#230]
Reported in Issue #223. Even with proper parameters, SDF can be leaked from ImplicitTriangleMesh3.

**Comment by doyubkim** [comment]
The root cause of the problem reported in #223 is due to the CustomImplicitSurface3 not returning optimal closest point during the collision handling especially when the query point is outside the bounding box of CustomImplicitSurface3. A workaround for ImplicitTriangleMesh3 (and address leaky particles in #223) is to use explicit mesh for non-SDF queries. This doesn't solve CustomImplicitSurface3 itself, though. Will land the workaround first, and seek for better solution for CustomImplicitSurface3.

**Comment by doyubkim** [comment]
Leaving some lengthy note for future reference.

PR for the fix is posted. After more investigating, the root cause for this problem is due to the inaccurate SDF when it's far from the surface. The original code is using closest point and normal to determine whether a query point is inside or outside the surface from colliders, but such an approximated SDF was returning wrong query results, making inside tests to fail.

Some options are to make highly accurate SDF even from very far query points or make the gradient descent more robust. The first option may fix ImplicitTriangleMesh3 particularly, but not for any random SDFs. The latter option might improve the situation, but cannot guarantee 100% stability.

While I am not fully happy about current Surface2 and 3 APIs, the simplest solution would be simply making sub-classes of the Surface2 and 3 to run inside testing by itself if better implementation is possible with more knowledge on sub-classing geometry (as shown in PR #232). Again, the current state of the geometry API is not ideal, which I'd like to clean up a bit for v2, the proposed PR should fix the issue with minimal change to the code.

**Comment by doyubkim** [comment]
@PavelBlend, let me know if it solves your problem. At least from my tests, the issue is gone.

**Comment by PavelBlend** [comment]
Checked.
There is no leakage.
Thank!
