### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by doyubkim** [doyubkim/fluid-engine-dev#240]
Test with VS 2019 and make sure it builds without issues. Also when available, add VS 2019 to the CI config.

**Comment by utilForever** [comment]
I already use it! Welcome to VS 2019. :tada:
p.s. Azure Pipelines supports VS 2019.

**Comment by doyubkim** [comment]
Awesome, so have you tested Jet Framework on VS 2019? Also, would it make more sense to migrate to Azure Pipelines for Windows build test? (From 2015 to 2019)

**Comment by utilForever** [comment]
Sorry for delay. There was too much busy last week. I'll test it today. Note that Azure Pipeline's configuration is a bit complicated. Fortunately, I have already experienced it, so let me summarize how to configure it.

**Comment by doyubkim** [comment]
@utilForever no worries. We can also wait until Appveyor supports it (https://github.com/appveyor/ci/milestone/143)

**Comment by utilForever** [comment]
I built Jet framework (x64-Debug and x64-Release) on VS 2019 and seems no problem. :)

**Comment by utilForever** [comment]
Appveyor updated VS 2019 image. I'll push related PR next week. :)

**Comment by doyubkim** [comment]
Awesome, thanks!
