### ISSUE TITLE
generate a manifold mesh

### ISSUE THREAD

**Issue by PavelBlend** [doyubkim/fluid-engine-dev#241]
Now the fluid mesh is created with unlinked double vertices.
The problem is that in blender some modifiers (for example Smooth) require Manifold meshes.
Here is the current result:
![01](https://user-images.githubusercontent.com/7983249/55672713-dc93cd00-58a6-11e9-88a6-49df60e4d79a.jpg)
And you need this result:
![02](https://user-images.githubusercontent.com/7983249/55672716-e87f8f00-58a6-11e9-82c3-0656cfd06a84.jpg)
And the edges of the mesh are too sharp.
You need to make an option that removes double vertices and does not create sharp edges.

**Comment by doyubkim** [comment]
Thanks for reporting this! Yeah, at least the connectivity should’ve been consistent. Will add an option for that.
