### ISSUE TITLE
Active option instead of One Shot

### ISSUE THREAD

**Issue by PavelBlend** [doyubkim/fluid-engine-dev#242]
Now the emitters have the option One Shot.
But it is not very convenient to use.
You need to make the option Active / Enable instead of One Shot:
![01](https://user-images.githubusercontent.com/7983249/55672969-4a8dc380-58aa-11e9-9c75-a216c56863c5.gif)
The One Shot option needs to be removed.
But you need to create a new type of emitter, which will be called FluidFromObject or something else similar.
And this new type of emitter should have the option to_emit, which can be turned on at any time several times:
![02](https://user-images.githubusercontent.com/7983249/55673102-deac5a80-58ab-11e9-9263-542ea30877be.gif)
And prohibit this object from emitting particles until the to_emit option is turned off and then on again.
That is, between two to_emit = True, there must be at least one to_emit = False.

**Comment by doyubkim** [comment]
Thank you for the suggestion. Any API removal would happen for major version update, but we can still introduce the new method (ie on/off switch) and put future-deprecation warning for the old one (is_one_shot).

**Comment by doyubkim** [comment]
@PavelBlend: I created a branch to add this feature (`fix-242`). All the emitters have `isEnabled` property to turn on and off an emitter. I need to add more unit tests, but feel free to test it out.

**Comment by PavelBlend** [comment]
I checked. Everything works correctly if you disable the OneShot option. But I can’t get the effect shown in the second gif image. That is, you can not emit particles not from the zero frame (with OneShot enabled). And you cannot re-emit particles from the same object if the OneShot option is enabled. It seems to me that it would be possible to rename the OneShot option to SingleShot (or something similar). And to make it so that it would be possible to emit particles from any frame (and not just from zero). And make it so that you can re-emit particles from the same object. I think you can make the function to_emit, which exhausts the particles during the simulation in any frame. And you can divide the Emitter class into two classes: Inflow (with the Enable option and without the to_emit function) and Emitter (without the Enable option, but with the to_emit function).

**Comment by doyubkim** [comment]
To avoid breaking the API while we are still in v1.x, I've updated the branch with the following changes:

- `emitter.isEnabled`: A new flag toggles the emitter entirely. (Included in the first commit.)
- `emitter.isOneShot`: Having this flag `True` disables the emitter after single emission by setting `isEnabled` to `False`, which is the new behavior. By setting `isEnabled` to `True` again, the emitter will get triggered one more time.

Here's a code snippet from newly added unit test demonstrating the new behavior:

```python
    # One-shot emitter
    emitter3 = pyjet.VolumeParticleEmitter3(
        implicitSurface=sphere,
        maxRegion=pyjet.BoundingBox3D((-1, -2, -3), (4, 2, 9)),
        spacing=0.1,
        initialVelocity=(-1, 0.5, 2),
        linearVelocity=(3, 4, 5),
        angularVelocity=(6, 7, 8),
        maxNumberOfParticles=300000,
        jitter=0.01,
        isOneShot=True,
        allowOverlapping=True,
        seed=42)

    # Emit some particles
    frame = pyjet.Frame()
    solver = pyjet.ParticleSystemSolver3()
    solver.emitter = emitter3
    solver.update(frame)
    frame.advance()
    assert solver.particleSystemData.numberOfParticles > 0
    assert not emitter3.isEnabled

    # Should not emit more particles
    old_num_particles = solver.particleSystemData.numberOfParticles
    solver.update(frame)
    frame.advance()
    assert solver.particleSystemData.numberOfParticles == old_num_particles

    # Re-enabling the emitter should make it emit one more time
    emitter3.isEnabled = True
    old_num_particles = solver.particleSystemData.numberOfParticles
    solver.update(frame)
    frame.advance()
    assert solver.particleSystemData.numberOfParticles > old_num_particles
```

**Comment by PavelBlend** [comment]
This is what I needed. Thank. Everything works correctly.

**Comment by doyubkim** [comment]
Thanks @PavelBlend! I've posted a PR.
