### ISSUE TITLE
Is this a bug in the function intersectsLocal of Cylinder3 class

### ISSUE THREAD

**Issue by ZeusYang** [doyubkim/fluid-engine-dev#251]
```C++
bool Cylinder3::intersectsLocal(const Ray3D& ray) const {
    ....
    if (pointOnCylinder.y >= center.y - 0.5 * height ||
        pointOnCylinder.y <= center.y + 0.5 * height) 
    {
            return true;
    }
    ....
}
```
It seems that here "||" should be "&&". Because intersection between the ray and the cylinder occurs when pointOnCylinder.y is in the interval [center.y - 0.5 * height, center.y + 0.5 * height].
Thanks.

**Comment by doyubkim** [comment]
Yup, that does sound like a bug! Thanks for finding this. It was also missing from any unit tests. Nice catch!

**Comment by doyubkim** [comment]
PR posted (#253), waiting for review (cc @utilForever).

**Comment by utilForever** [comment]
I merged PR. Please confirm it. :)
