### ISSUE TITLE
Water-drop

### ISSUE THREAD

**Issue by xiaoxiaoyu1872** [doyubkim/fluid-engine-dev#252]
I want to simulate the phenomenon of water splash.
But I found that to set the droplet velocity, the droplet and the pool velocity have to be set together.
How to solve this problem?  thank you.
example:
    auto box = Box3::builder()
                .withLowerCorner({0, 0, 0})
                .withUpperCorner({1, 0.5, 1})
                .makeShared();                  
    auto droplet = Sphere3::builder()
                      .withCenter(domain.midPoint())
                      .withRadius(0.15 * domain.width())
                      .makeShared();
   auto surfaceSet1 = ImplicitSurfaceSet3::builder()
                       .withExplicitSurfaces({box})
                       .makeShared();

    auto surfaceSet2 = ImplicitSurfaceSet3::builder()
                      .withExplicitSurfaces({droplet})
                      .makeShared();
   auto emitter2 = VolumeParticleEmitter3::builder()
                       .withImplicitSurface(surfaceSet2)
                       .withSpacing(targetSpacing)
                       .withMaxRegion(sourceBound)
                       .withIsOneShot(true)
                       .makeShared();
   auto vec = Vector3D({0,-4,0});
   auto emitter2 = VolumeParticleEmitter3::builder()
                       .withImplicitSurface(surfaceSet2)
                       .withSpacing(targetSpacing)
                       .withMaxRegion(sourceBound)
                       .withIsOneShot(true)
                       .withInitialVelocity(vec)
                       .makeShared();
solver->setEmitter(emitter1);solver->setEmitter(emitter2);

**Comment by doyubkim** [comment]
Thanks for the great question!

If you use `ImplicitSurfaceSet3`, it means the entire surfaces you added to the set will be treated as a single surface. If you want to use different emitter properties, you need to
1. Create two surfaces.
2. Create two `VolumeParticleEmitter3` with one surface for each. Assign different velocities for each of the emitters.
3. Create `ParticleEmitterSet3` and add these emitters.
4. Call `solver->setEmitter` with the `ParticleEmitterSet3` instance above.

Hope that helps!

**Comment by xiaoxiaoyu1872** [comment]
i have solved this problem, thanks a lot

**Comment by doyubkim** [comment]
Great! Closing this issue then.
