### ISSUE TITLE
The second derivative of poly6 kernel function.

### ISSUE THREAD

**Issue by ZeusYang** [doyubkim/fluid-engine-dev#254]
Hello, douyubkim. I just discoverd the following problems. 
It is about the second derivative of poly6 kernel function. In your code: 
```C++
inline double SphStdKernel3::secondDerivative(double distance) const {
    if (distance * distance >= h2) {
        return 0.0;
    } else {
        double x = distance * distance / h2;
        return 945.0 / (32.0 * kPiD * h5) * (1 - x) * (3 * x - 1);
    }
}
```
But I calculated it by hands for serveral times and wrote a different version:
```C++
inline double SphStdKernel3::secondDerivative(double distance) const {
    if (distance * distance >= h2) {
        return 0.0;
    } else {
        double x = distance * distance / h2;
        return 945.0 / (32.0 * kPiD * h5) * (1 - x) * (5 * x - 1);
    }
}
```
It's just 3 should be replaced with 5 in that equation. I know it was missing from any test because we just use the second derivative of spiky kernel function instead of poly6 kernel function.

Meanwhile, there is also a small mistake on Page 133 of your book. It's about formula (2.9), the equation of state. I check out the paper (Becker M, Teschner M. Weakly compressible SPH for free surface flows[C]//Proceedings of the 2007 ACM SIGGRAPH/Eurographics symposium on Computer animation. Eurographics Association, 2007: 209-217.) and find that you just put the gamma exponent in the wrong place. The code shown in the book is right.

Thanks.

**Comment by yanwc** [comment]
@doyubkim, I'm so glad to help you. 
For the first problem I mentioned above, I think you also need to publish an update in your error collection web page since the code is shown on Page 127.

I got another two typos of your book. 
On Page 137, the formula (2.14), you forgot the square symbol of m. But the code in the page is right.
On Page 134, the formula (2.10), you also forgot the square symbol of c and the code is right.

And I feel a little confused about the eos scaling coefficient of the equation of state. 
In the paper: http://cg.informatik.uni-freiburg.de/publications/2007_SCA_SPH.pdf
The coefficient is
$$  \rho_0\frac{c_s^2}{\gamma} $$
But in the book, according the formula (2.9) and the formula (2.10), the coefficient becomes 
$$ \rho_0\frac{c_s^2}{\gamma^2} $$
That is, the latter formula is divided by square of gamma .  So is this a mistake or innovation?

**Comment by yanwc** [comment]
Yeah, I also think it might be some sort of mixed up. And finally, I make a experiment about that coefficient.  I just wanted to compare the difference between them. And so I removed the divisor eosExpoent:
```C++
inline double computePressureFromEos(
	double density,
	double targetDensity,
	double eosScale,
	double eosExponent,
	double negativePressureScale) {
	// Equation of state
	// (http://www.ifi.uzh.ch/vmml/publications/pcisph/pcisph.pdf)

	// Before
	//double p = eosScale / eosExponent
	//	* (std::pow((density / targetDensity), eosExponent) - 1.0);

	// After
	double p = eosScale
		* (std::pow((density / targetDensity), eosExponent) - 1.0);

	// Negative pressure scaling
	if (p < 0) {
		p *= negativePressureScale;
	}

	return p;
}
```
Then I used the PCISPH solver to simulate the dam breaking scene, and I got the following two results. I don't think there exists obvious difference.  It looks like the solver isn't sensitive to this modification at all. The first gif is no modification but the second one is.

![1](https://user-images.githubusercontent.com/32561301/63833002-8c77ed00-c9a4-11e9-946a-4e21d1eef6ca.gif)
![2](https://user-images.githubusercontent.com/32561301/63833011-900b7400-c9a4-11e9-9df7-52847b1d1343.gif)

**Comment by yanwc** [comment]
@doyubkim  Do the gifs display normal?

**Comment by yanwc** [comment]
> Thanks for testing the fix with full sim! Yes, it doesn't make any noticeable difference from this particular tests which is a good sign. I think factor of 7 (the default gamma value) didn't make Tait equation stiff enough for given time-steps, which makes sense because the time-step is controlled dynamically.

Yes, it does. I can't agree more.  Adaptive time controlling plays a significant role.  It's my great honour to help this out. Fluid Simulation is  so funny and I am really grateful to you for your book and code.

**Comment by doyubkim** [comment]
Thanks! Please feel free to report any other errata or bugs.

**Comment by doyubkim** [comment]
Thank you again, @ZeusYang, for the careful derivation and for testing the EOS correction with a complete simulation.

I revisited all of the book-related findings in this issue while preparing the second edition.

The second derivative of the 3D Poly6 kernel should contain the factor `(5 * x - 1)`. The corresponding expression and book listing will be corrected in the second edition.

The Tait equation will be written as

$$
p = \frac{\kappa}{\gamma}
\left[
\left(\frac{\rho}{\rho_0}\right)^\gamma - 1
\right],
\qquad
\kappa = \rho_0 c_s^2.
$$

The related missing square on $m$, the missing viscosity coefficient, and the missing square on $c_s$ will also be corrected.

Thank you for finding these mathematical errors and for providing detailed explanations.
