### ISSUE TITLE
LevelSetLiquidSolver3 reset air velocity in grid

### ISSUE THREAD

**Issue by kentbarber** [doyubkim/fluid-engine-dev#265]
Hi Doyub,

I have a LevelSetLiquidSolver3 where it has multiple emitters in a GridEmitterSet3. When the emitters are enabled midway during a simulation they are getting affected immediately by what I believe to be the air velocity of the cells. Is there any way you can think of to avoid this? Perhaps reset the velocity of newly emitted cells?

![levelsetissue](https://user-images.githubusercontent.com/12145275/68257593-b03c6b00-0098-11ea-97da-b6641328bb1e.gif)

Thanks again for all your work.

Best Regards,
Kent

**Comment by kentbarber** [comment]
Actually you can ignore this. I think I should be able to make them colliders first, then disable the colliders and emit. I will close this thread now.

**Comment by kentbarber** [comment]
Reopening this again. It doesn’t look like I can disable a collider. Would this be possible to do?

**Comment by doyubkim** [comment]
Thank you for finding this bug, @kentbarber! I think there's a bug when the emitter injects the SDF where it doesn't update the velocity field properly. I will look into this.

**Comment by doyubkim** [comment]
Hi @kentbarber,

So I think this is more like an API bug/issue where adding emitter for grid-based solvers is not consistent with particle-based solver. Before I explain further, you should try the following.

In your code, I guess you are adding an emitter like this:

```cpp
solver->setEmitter(emitter);
emitter->addSignedDistanceTarget(solver->signedDistanceField());
```

The code above only adds an SDF geometry, but doesn't specify the velocity field (not even zero). So in your case where the emitter should add zero-velocity object to the scene, you should add additional emitter target such as:

```cpp
solver->setEmitter(emitter);
emitter->addSignedDistanceTarget(solver->signedDistanceField());
emitter->addTarget(
    solver->velocity(),
    [](double sdf, const Vector3D& pt, const Vector3D& oldVal) {
        if (sdf < 0.0) {
            return Vector3D(0, 0, 0);
        } else {
            return Vector3D(oldVal);
        }
    });
```

The code above explicitly tell the emitter how to handle velocity field. Can you try it and see if it addresses your issue?

I know the emitter APIs in general (including the particle ones) are far from ideal and hoping to address this in the next version. If the code above works for you, I will post a new issue to specifically track this grid emitter API problem.

**Comment by kentbarber** [comment]
Hi @doyubkim,

That worked perfectly. Thank you.

I was also wondering if it is possible to add new emitters to the emitterset during the simulation? Since these steps outlined here are all performed before the solver->update method is called. I will try this later this week and if I see problems I will open a new issue.

Cheers,
Kent

**Comment by doyubkim** [comment]
Emitters and colliders should be updated every frame before it actually advances a fluid-sim time-step. (More specifically, when `beginAdvanceTimeStep` is called internally.) So setting a new emitter at random frame should work:

```cpp
solver->setEmitter(emitter);
emitter->addSignedDistanceTarget(solver->signedDistanceField());
emitter->addTarget(
    solver->velocity(),
    [](double sdf, const Vector3D& pt, const Vector3D& oldVal) {
        if (sdf < 0.0) {
            return Vector3D(0, 0, 0);
        } else {
            return Vector3D(oldVal);
        }
    });
```
> So basically you are throwing away old emitter which is completely fine.

If not, please open a new issue! :)

**Comment by kentbarber** [comment]
Great. I will give it a try. I am going to see if I can get it working with the MoGraph system in C4D to dynamically add fluid to a sim.
