### ISSUE TITLE
How to properly read these codes?

### ISSUE THREAD

**Issue by ouroboros1221** [doyubkim/fluid-engine-dev#275]
It would be so much easier if it's an QT project, I could open the .pro project file and see how everything's linked at a glance. Now when I try to dive into individual .cpp or .h header files to study the code, I found one header file is sourcing in another headerfile, and another headerfile is sourcing in again from another header file,  this is really frustrating from a code dissection point of view. For example, I'm reading the chapter about sph 2d solver and its working algorithm, so naturally I want to just follow the example and build the code and see the result, but because of those nested header files, I feel really disorienting and I gave up in the middle of manually linking those header file in their path. Is there a more learner oriented way to do this? Thanks.

**Comment by dokipen3d** [comment]
You can add a project to qtcreator without a .pro file and still be able to jump around with f2/f4 etc. You just add existing project add point it to the folder you want to read.
