### ISSUE TITLE
Jet.vis is missing

### ISSUE THREAD

**Issue by yangfengzzz** [doyubkim/fluid-engine-dev#281]
I would like to know if there are jet.vis files. I can't compile opengl_tests and a lot of imgui related examples. it is a depreciated feature or it is not commited into the git? THX

**Comment by doyubkim** [comment]
That’s probably from one of the dev branch. It shouldn’t be in the master. The dev branches are super unstable since it’s mainly used for experimental projects :)

**Comment by SeekPossibility** [comment]
> That’s probably from one of the dev branch. It shouldn’t be in the master. The dev branches are super unstable since it’s mainly used for experimental projects :)

Yes I'm on dev-v2-gpu branch. there are only jet.gfx but not jet.vis, especially there is no jet.viz/glfw_imgui_utils-ext.h . I don't know how to interact with ImGUI to display the log texts

**Comment by doyubkim** [comment]
Yup, that branch is out of date. Please do not use that branch until the build issues are being fixed.
