### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by sukbu** [doyubkim/fluid-engine-dev#285]
This repository is created and maintained by Doyub Kim (@doyubkim). Chris Ohk (@utilForever) is a co-developer of the framework since v1.3. Many other contributors also helped improving the codebase including Jefferson Amstutz (@jeffamstutz) who helped integrating **Inten TBB** and OpenMP backends.

Inten TBB => Intel TBB

**Comment by doyubkim** [comment]
Nice catch :) Will fix soon

**Comment by doyubkim** [comment]
Since buggy CI is now been fixed, let me rebase and push the pending fix.
