### ISSUE TITLE
where is Box2::closestNormal ?

### ISSUE THREAD

**Issue by yangfengzzz** [doyubkim/fluid-engine-dev#291]
I notice in Box2::closestIntersectionLocal, It will use Box2::closestNormal which is actually Surface2:: closestNormal, why there use this func, I think closestIntersectionLocal is done in local space not in the world space?

**Comment by doyubkim** [comment]
Hi @yangfengzzz! Yes, it should be in local space, thus it should use closetNormalLocal. Let me post a PR soon.

**Comment by yangfengzzz** [comment]
and in Cylinder3::closestIntersectionLocal, it use boundingBox() which is also in global space

**Comment by doyubkim** [comment]
PR is out

**Comment by doyubkim** [comment]
The fix is now merged!
