### ISSUE TITLE
Fixes for supporting MinGW-w64

### ISSUE THREAD

**Issue by cesss** [doyubkim/fluid-engine-dev#295]
If you want to cross-compile from any UNIX system to Windows, using MinGW-w64, you need to do the following fixes:

- In src/jet/pch.h src/jet/private_helpers.h, you need to perform the NOMINMAX definition only when using a Microsoft compiler (an #ifdef _MSC_VER will work).
- In src/jet/private_helpers.h, the throw std::exception with a string is not correct C++ code according to the standard (although Microsoft supports that). Using throw std::invalid_argument() for example will work. Again, you can use a different implementation for each compiler by using #ifdef _MSC_VER)
- In logging.cpp , the %F and %T formats are not supported by MinGW-w64 yet (there's a bug report [here](https://sourceforge.net/p/mingw-w64/bugs/793/)). As a workaround, it's possible to use the %Y-%m-%d %H:%M:%S format instead.
- As a workaround for [this problem](https://github.com/tsduck/tsduck/issues/205), the -Wno-deprecated-copy flag must be passed to the compiler.
- The "typedef SSIZE_T ssize_t;" line in include/jet/macros.h must be used for Microsoft compilers only (so, it can be put inside an #ifdef _MSC_VER as well.

With all of this, it builds fine. I still need to test it, but I hope it will work.

BTW, let me suggest to build the source with GCC 9.x on Linux, because it's quite likely that you'll hit the problem requiring the "-Wno-deprecated-copy" flag even on Linux if you use GCC 9 (my mingw-w64 is 9.2.0)

**Comment by doyubkim** [comment]
Thanks for reporting this! I haven't tried MinGW-w64, so needs to test the build on it. Setting up a proper CI will be more important in this case.

**Comment by cesss** [comment]
It seems it needs some work, because I'm getting 9 failures when running the unit tests. My advice is that you start by building it with GCC 9.x even on Linux, because I guess that the failure due to "deprecate copy" is not specific to MinGW-w64, but to GCC 9 (it's a warning, but you build with -Werror, so it breaks the build).

For the moment I don't consider building Jet on Windows a priority, but I suggest you to support cross-compiling (many developers build for Windows that way)

**Comment by doyubkim** [comment]
BTW, that GCC9 error comes solely from gtest (which is discussed in a separate Issue #296) which needs to be updated to the latest release. There is another PR (#297) that fixes the issue while trying to support Ubuntu 20.04 LTS (which also defaults its gcc to 9.x).

**Comment by doyubkim** [comment]
The fix is now merged!
