### ISSUE TITLE
render manual tests root path

### ISSUE THREAD

**Issue by igbondar** [doyubkim/fluid-engine-dev#301]
Hi! 
It is probably not very important, just a side note. 

I ran this script **render_manual_tests_output.py** on windows 10 but it didn't do anything.
The root path is one word it always returns empty list.
filenames = utils.get_all_files('manual_tests_output', ['*' + render.INPUT_ARRAY_FORMAT])

Full root path works fine.

**Comment by doyubkim** [comment]
Uh oh! Let me see what’s going on. Thanks for reporting this issue!

**Comment by doyubkim** [comment]
Hi @igbondar ! I just tried on my Windows machine, but I couldn't reproduce the issue.
But based on what you said, can you double check which directory are you running the `manual_tests.exe` and `render_manual_tests_output.py`? Both should be called from the same directory.

**Comment by igbondar** [comment]
Hi @doyubkim !
It is working fine if I run it from manual_tests.exe directory. 
Wasn't clear from webhelp about this restriction,
Thanks!

**Comment by doyubkim** [comment]
Actually it doesn’t have to be in the directory where the exe file exists. Where you run the python script should be the directory where manual_tests_output exists. Please let me know if you still have the issue!
