### ISSUE TITLE
Suggestion to replace Travis CI/Appveyor with GitHub Actions

### ISSUE THREAD

**Issue by utilForever** [doyubkim/fluid-engine-dev#312]
Have you ever seen a [The new pricing model for travis-ci.com](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)?
The new pricing model is based on credits. Maybe you're using credit by Trial Plan now. For OSS purposes, it is said that you must apply via e-mail. Therefore, I would like to suggest replacing existing CIs with GitHub Actions. What do you think about this?

**Comment by doyubkim** [comment]
Yeah I heard about it today as well. It's frustrating tbh, but a good chance to migrate to Github Actions. Will work on it.

**Comment by utilForever** [comment]
I already replaced them with GitHub Actions. I can work! 😄

**Comment by doyubkim** [comment]
Ok I will reassign it to you. Thanks!

**Comment by doyubkim** [comment]
@utilForever Do you have any update on this? Thanks again for taking this issue!

**Comment by utilForever** [comment]
@doyubkim Nah, I forgot it! 😭 I'll work this ASAP. Thanks.
