### ISSUE TITLE
running the Python example show error

### ISSUE THREAD

**Issue by xiaomintongxue** [doyubkim/fluid-engine-dev#320]
running the example use "python src/examples/python_examples/smoke_example01.py" in  the  windows, shows the error like:Traceback (most recent call last):
  File "src/examples/python_examples/smoke_example01.py", line 11, in <module>
    from pyjet import *
  File "<frozen importlib._bootstrap>", line 1031, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 1026, in _handle_fromlist
TypeError: Item in pyjet.__all__ must be str, not dtype[void]

what's the problem？

really thanks~~

**Comment by doyubkim** [comment]
Uh oh. Let me check and see what's going on. Thanks!

**Comment by doyubkim** [comment]
@xiaomintongxue I wasn't able to reproduce the error. Which platform/python environment did you use? Do you mind sharing the steps (command line commands) you used?

**Comment by xiaomintongxue** [comment]
the Python is Python3.7（64-bit Windows），and i think i have already installed the packages ，it show in the following.
pip freeze



aiohttp==3.7.4.post0
anyio==3.3.0
argon2-cffi==20.1.0
asgiref==3.3.4
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
autobahn==21.3.1
Automat==20.2.0
Babel==2.9.1
backcall==0.2.0
beautiful==0.0.2
beautifulsoup4==4.9.3
bleach==4.0.0
bs4==0.0.1
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
colorama==0.4.4
constantly==15.1.0
cryptography==3.4.7
cycler==0.10.0
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
Django==3.2.4
easygui==0.98.2
entrypoints==0.3
flake8==3.9.2
gmsh==4.7.1
hyperlink==21.0.0
idna==2.10
importlib-metadata==3.10.1
importlib-resources==5.2.0
incremental==21.3.0
ipykernel==6.0.3
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
jieba==0.42.1
Jinja2==3.0.1
json5==0.9.6
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.2.0
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-server==1.10.2
jupyterlab==3.1.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.7.0
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mccabe==0.6.1
meshio==4.4.6
mfem==0.0.3
mistune==0.8.4
mpmath==1.2.1
multidict==5.1.0
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.3
numpy==1.20.3
opencv-python==4.5.2.52
packaging==21.0
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
pickleshare==0.7.5
Pillow==8.2.0
prettytable==2.1.0
prometheus-client==0.11.0
prompt-toolkit==3.0.19
pycodestyle==2.7.0
pycparser==2.20
pyecharts==1.9.0
pyflakes==2.3.1
Pygments==2.9.0
pygmsh==7.1.10
pyjet==1.8.2
pymesh==1.0.2
pymongo==3.11.4
PyMySQL==1.0.2
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.1
pytz==2021.1
pywin32==301
pywinpty==1.1.3
pyzmq==22.2.1
qtconsole==5.1.1
QtPy==1.9.0
requests==2.25.1
requests-unixsocket==0.2.0
scipy==1.6.3
Send2Trash==1.8.0
simplejson==3.17.2
six==1.16.0
sniffio==1.2.0
solidspy==1.0.16
soup==0.1.0
soupsieve==2.2.1
sqlparse==0.4.1
sympy==1.8
terminado==0.10.1
testpath==0.5.0
torch==1.9.0
tornado==6.1
traitlets==5.0.5
Twisted==21.7.0
twisted-iocpsupport==1.0.1
txaio==21.2.1
typing-extensions==3.10.0.0
urllib3==1.26.5
vtk==9.0.3
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.0
widgetsnbextension==3.5.1
wordcloud==1.8.1
wslink==1.0.5
xlrd==2.0.1
xlwings==0.23.3
xlwt==1.3.0
yapf==0.31.0
yarl==1.6.3
zipp==3.4.1
zope.interface==5.4.0


 Allen Chiang
***@***.***
On 8/22/2021 16:07，Doyub ***@***.***> wrote：

@xiaomintongxue I wasn't able to reproduce the error. Which platform/python environment did you use? Do you mind sharing the steps (command line commands) you used?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by doyubkim** [comment]
Ok I think you got the other "pyjet". Unfortunately that name is reserved by other library with the same name. You can uninstall existing pyjet from your environment and reinstall Jet Framework by running "pip install -U ." inside this repo directory (assuming you already git cloned it). 

Hope this helps and let me know if you still encounter an issue.

**Comment by xiaomintongxue** [comment]
really thanks~~
On 8/23/2021 10:26，Doyub ***@***.***> wrote：

Ok I think you got the other "pyjet". Unfortunately that name is reserved by other library with the same name. You can uninstall existing pyjet from your environment and reinstall Jet Framework by running "pip install -U ." inside this repo directory (assuming you already git cloned it).

Hope this helps and let me know if you still encounter an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaomintongxue** [comment]
sorry ，i think i dont solve the problem.
In project depository i have used the code to install the package.


python setup.py install


shows the errors in the following.
（plus：In the CMakeOutput.log show  the system is: Windows - 10.0.19042 - AMD64，
that's my computer system. where is the problem？very precious your help~）


running install
running bdist_egg
running egg_info
writing pyjet.egg-info\PKG-INFO
writing dependency_links to pyjet.egg-info\dependency_links.txt
writing top-level names to pyjet.egg-info\top_level.txt
reading manifest file 'pyjet.egg-info\SOURCES.txt'
writing manifest file 'pyjet.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
CMake Error at CMakeLists.txt:16 (project):
 Generator

   NMake Makefiles

 does not support platform specification, but platform

   x64

 was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/jiangms/Desktop/fluid-engine-dev-main/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
 File "setup.py", line 90, in
   zip_safe=False,
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\__init__.py", line 145, in setup
   return distutils.core.setup(**attrs)
 File "D:\Program Files\Pyt3\lib\distutils\core.py", line 148, in setup
   dist.run_commands()
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 966, in run_commands
   self.run_command(cmd)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install.py", line 67, in run
   self.do_egg_install()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
   self.run_command('bdist_egg')
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
   cmd = self.call_command('install_lib', warn_dir=0)
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
   self.run_command(cmdname)
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
   self.build()
 File "D:\Program Files\Pyt3\lib\distutils\command\install_lib.py", line 107, in build
   self.run_command('build_ext')
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "setup.py", line 43, in run
   self.build_extension(ext)
 File "setup.py", line 76, in build_extension
   cmake_args, cwd=self.build_temp, env=env)
 File "D:\Program Files\Pyt3\lib\subprocess.py", line 347, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=D:\\Program Files\\Pyt3\\python.exe', '-DBUILD_FROM_PIP=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.

C:\Users\jiangms\Desktop\fluid-engine-dev-main>cmake -G "NMake Makefiles" ..
CMake Error: The source directory "C:/Users/jiangms/Desktop" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.


———————————————————
On 8/23/2021 10:26，Doyub ***@***.***> wrote：

Ok I think you got the other "pyjet". Unfortunately that name is reserved by other library with the same name. You can uninstall existing pyjet from your environment and reinstall Jet Framework by running "pip install -U ." inside this repo directory (assuming you already git cloned it).

Hope this helps and let me know if you still encounter an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaomintongxue** [comment]
The problem have been solved and i can run the examples successful.  
The  reason is that i have used the download zip not the git tool, the file is not incomplete.
i am very sorry to disturb all of you.


Very  thanks~




On 8/25/2021 ***@***.***> wrote：
sorry ，i think i dont solve the problem.
In project depository i have used the code to install the package.


python setup.py install


shows the errors in the following.
（plus：In the CMakeOutput.log show  the system is: Windows - 10.0.19042 - AMD64，
that's my computer system. where is the problem？very precious your help~）


running install
running bdist_egg
running egg_info
writing pyjet.egg-info\PKG-INFO
writing dependency_links to pyjet.egg-info\dependency_links.txt
writing top-level names to pyjet.egg-info\top_level.txt
reading manifest file 'pyjet.egg-info\SOURCES.txt'
writing manifest file 'pyjet.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
CMake Error at CMakeLists.txt:16 (project):
 Generator

   NMake Makefiles

 does not support platform specification, but platform

   x64

 was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/jiangms/Desktop/fluid-engine-dev-main/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
 File "setup.py", line 90, in
   zip_safe=False,
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\__init__.py", line 145, in setup
   return distutils.core.setup(**attrs)
 File "D:\Program Files\Pyt3\lib\distutils\core.py", line 148, in setup
   dist.run_commands()
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 966, in run_commands
   self.run_command(cmd)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install.py", line 67, in run
   self.do_egg_install()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
   self.run_command('bdist_egg')
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
   cmd = self.call_command('install_lib', warn_dir=0)
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
   self.run_command(cmdname)
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "D:\Program Files\Pyt3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
   self.build()
 File "D:\Program Files\Pyt3\lib\distutils\command\install_lib.py", line 107, in build
   self.run_command('build_ext')
 File "D:\Program Files\Pyt3\lib\distutils\cmd.py", line 313, in run_command
   self.distribution.run_command(command)
 File "D:\Program Files\Pyt3\lib\distutils\dist.py", line 985, in run_command
   cmd_obj.run()
 File "setup.py", line 43, in run
   self.build_extension(ext)
 File "setup.py", line 76, in build_extension
   cmake_args, cwd=self.build_temp, env=env)
 File "D:\Program Files\Pyt3\lib\subprocess.py", line 347, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=D:\\Program Files\\Pyt3\\python.exe', '-DBUILD_FROM_PIP=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\jiangms\\Desktop\\fluid-engine-dev-main\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.

C:\Users\jiangms\Desktop\fluid-engine-dev-main>cmake -G "NMake Makefiles" ..
CMake Error: The source directory "C:/Users/jiangms/Desktop" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.


———————————————————
On 8/23/2021 10:26，Doyub ***@***.***> wrote：

Ok I think you got the other "pyjet". Unfortunately that name is reserved by other library with the same name. You can uninstall existing pyjet from your environment and reinstall Jet Framework by running "pip install -U ." inside this repo directory (assuming you already git cloned it).

Hope this helps and let me know if you still encounter an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by doyubkim** [comment]
Great to hear @xiaomintongxue ! Let me know if you run into any other problems.
