### ISSUE TITLE
The Visual Studio project is completely broken

### ISSUE THREAD

**Issue by cabreak2** [doyubkim/fluid-engine-dev#65]
A bunch of library and header includes are missing, syntax errors, ... too many to fix myself.

**Comment by doyubkim** [comment]
Thanks for submitting the issue! Are you using VS 2015? It could be possible that the NuGet package (for zlib) is not properly downloaded when building the code (such as network hiccup while compiling). Can you paste your error message here?

**Comment by doyubkim** [comment]
I think PR #66 is a related fix. Since it's passing CI I'm closing this issue. But feel free to reopen with error logs if you see a different problem.
