### ISSUE TITLE
APIC Solver numerical dissipation?

### ISSUE THREAD

**Issue by aneeshvaidya** [doyubkim/fluid-engine-dev#94]
I was going over the rotation manual tests, and while it seems the dissipation is less than PIC or FLIP as expected, I thought that the dissipation would be much less than it is since APIC is supposed to preserve angular momentum? Is this a bug or am I missing something conceptually?

**Comment by doyubkim** [comment]
@aneeshvaidya, thanks for reporting this. It could be a test issue if I see other APIC test results which show low dissipation. Let me take a look.

**Comment by aneeshvaidya** [comment]
In the Apic Solver 2d rotation test, I commented out the following line: 

`solver->setPressureSolver(nullptr);`

And there was significantly reduced dissipation. Not sure what this means, but I think it may have to do with the pressure projection correcting the velocities, allowing momentum conservation?

**Comment by doyubkim** [comment]
@aneeshvaidya, you're right. So the intention of that piece of code was to eliminate everything else except APIC transfer (grid <-> particles) and put position constraint (line 91 to 95 of apic_solver2_tests.cpp) to apply rigid body constraint. That position constraint part can cause a projection error, and as you observed, solving pressure step will make the particles to stay in the circular course and thus less projection error. Let me remove that line.
