### ISSUE TITLE
Visualize XYZ particles

### ISSUE THREAD

**Issue by marcelsan** [doyubkim/fluid-engine-dev#98]
Hello,

I ran the sph_sim example and it generated an output folder with a lot of .xyz files which i believe are the positions of particles for each frame. Is there any script to generate a .mp4 animation based on this .xyz files?

Thank you!

**Comment by doyubkim** [comment]
Hi!

I don't have such a script right now, but should be pretty straightforward with Matplotlib. Let me write something and post it to the repo soon. 

Thanks!

**Comment by marcelsan** [comment]
Hi,

I wrote a code which uses matplotlib to do this. I gonna post it here today.
